// <auto-generated />
using System;
using AdVideo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdVideo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdVideoDbContext))]
    [Migration("20260926023914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdVideo.Core.Entities.AdVideoJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("AspectRatio")
                        .HasColumnType("int");

                    b.Property<string>("BriefJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("FinalVideoAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormatCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("HasPerson")
                        .HasColumnType("bit");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderModelId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawProviderError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegenerateCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubtitleAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermsAcceptedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("ThumbnailAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoiceAudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoiceProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_AdVideoJobs_Status_CreatedAt");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_AdVideoJobs_Tenant_CreatedAt")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_AdVideoJobs_Tenant_IdempotencyKey")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("AdVideoJobs", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.AdVideoProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultBrandKitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_AdVideoProjects_Tenant_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("AdVideoProjects", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DerivedFromAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<bool>("HasAudio")
                        .HasColumnType("bit");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQcPassed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecksumSha256")
                        .HasDatabaseName("IX_MediaAssets_Checksum");

                    b.HasIndex("DerivedFromAssetId");

                    b.HasIndex("JobId", "Kind")
                        .HasDatabaseName("IX_MediaAssets_Job_Kind");

                    b.HasIndex("TenantId", "Kind")
                        .HasDatabaseName("IX_MediaAssets_Tenant_Kind")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Example")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_PromptTemplates_Code_Active")
                        .HasFilter("[IsActive] = 1 AND [IsDeleted] = 0");

                    b.HasIndex("Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_PromptTemplates_Code_Version")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PromptTemplates", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.ProviderCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int?>("BilledCharacterCount")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("CostIsReported")
                        .HasColumnType("bit");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptorSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("FailureKind")
                        .HasColumnType("int");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShotIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "CreatedAt")
                        .HasDatabaseName("IX_ProviderCalls_Job_CreatedAt");

                    b.HasIndex("Provider", "CreatedAt")
                        .HasDatabaseName("IX_ProviderCalls_Provider_CreatedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Provider", "CreatedAt"), new[] { "CostUsd" });

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_ProviderCalls_Tenant_CreatedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "CreatedAt"), new[] { "CostUsd" });

                    b.ToTable("ProviderCalls", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.ProviderCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilityJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreditExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DailyCostLimitUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndpointUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Category", "IsActive", "Priority")
                        .HasDatabaseName("IX_ProviderCredentials_Category_Active_Priority")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Provider", "ModelId", "Category", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProviderCredentials_Provider_Model_Category_Tenant")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ProviderCredentials", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.ProviderDescriptorRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ProviderDescriptors_Code_Active")
                        .HasFilter("[IsActive] = 1 AND [IsDeleted] = 0");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("IX_ProviderDescriptors_Sha256");

                    b.HasIndex("Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_ProviderDescriptors_Code_Version")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ProviderDescriptors", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.Shot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AudioStartInTimelineSeconds")
                        .HasColumnType("float");

                    b.Property<Guid?>("ClipAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsLipSynced")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("NarrationEndSeconds")
                        .HasColumnType("float");

                    b.Property<double>("NarrationStartSeconds")
                        .HasColumnType("float");

                    b.Property<Guid?>("NativeAudioAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Padding")
                        .HasColumnType("int");

                    b.Property<string>("ProviderModelId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RenderFinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RenderStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int?>("Seed")
                        .HasColumnType("int");

                    b.Property<string>("SpokenText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TtsRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VideoDurationSeconds")
                        .HasColumnType("int");

                    b.Property<double>("VideoStartSeconds")
                        .HasColumnType("float");

                    b.Property<string>("VisualPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClipAssetId");

                    b.HasIndex("NativeAudioAssetId");

                    b.HasIndex("JobId", "Index")
                        .IsUnique()
                        .HasDatabaseName("UX_Shots_Job_Index");

                    b.HasIndex("Status", "RenderStartedAt")
                        .HasDatabaseName("IX_Shots_Status_RenderStartedAt");

                    b.ToTable("Shots", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaxValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MinValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_SystemSettings_Key")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ApiKeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("ApiKeyRotatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("UX_Tenants_ApiKeyPrefix")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("AdVideo.Core.Entities.AdVideoJob", b =>
                {
                    b.HasOne("AdVideo.Core.Entities.AdVideoProject", "Project")
                        .WithMany("Jobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AdVideo.Core.Entities.AdVideoProject", b =>
                {
                    b.HasOne("AdVideo.Core.Entities.Tenant", null)
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdVideo.Core.Entities.MediaAsset", b =>
                {
                    b.HasOne("AdVideo.Core.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("DerivedFromAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdVideo.Core.Entities.AdVideoJob", "Job")
                        .WithMany("Assets")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("AdVideo.Core.Entities.ProviderCall", b =>
                {
                    b.HasOne("AdVideo.Core.Entities.AdVideoJob", "Job")
                        .WithMany("ProviderCalls")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("AdVideo.Core.Entities.Shot", b =>
                {
                    b.HasOne("AdVideo.Core.Entities.MediaAsset", "ClipAsset")
                        .WithMany()
                        .HasForeignKey("ClipAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdVideo.Core.Entities.AdVideoJob", "Job")
                        .WithMany("Shots")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdVideo.Core.Entities.MediaAsset", "NativeAudioAsset")
                        .WithMany()
                        .HasForeignKey("NativeAudioAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClipAsset");

                    b.Navigation("Job");

                    b.Navigation("NativeAudioAsset");
                });

            modelBuilder.Entity("AdVideo.Core.Entities.AdVideoJob", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ProviderCalls");

                    b.Navigation("Shots");
                });

            modelBuilder.Entity("AdVideo.Core.Entities.AdVideoProject", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("AdVideo.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
